<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="chrome=1;">
		<title>Gallery of images in your mailbox</title>
<?php /*
		<link rel="stylesheet" type="text/css" href="/css/common.css" />
		<link rel="stylesheet" type="text/css" href="/css/app.css" />

		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/<?php echo LIBRARY_VERSION_JQUERY; ?>/jquery.min.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/<?php echo LIBRARY_VERSION_JQUERYUI; ?>/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/js/jquery.ba-hashchange.min.js"></script>
		<script type="text/javascript" src="/js/dateToLocaleFormat.js"></script>
		<script type="text/javascript" src="/js/app.js"></script>
		*/ ?>
	</head>
	<body>
		<?php echo $bodyContent; ?>
	</body>
</html>